### ISSUE TITLE
File gatsby-node.js is missing when plugin is installed

### ISSUE THREAD

**Issue by ronaldborman** [kamranayub/gatsby-source-typedoc#1]
When I install the plugin with the commands mentioned in the Example Usage section, the directory gatsby-source-typedoc in node_modules looks like this:
-- .eslintrc.json
-- .travis.yml
-- CHANGELOG.md
-- index.js
-- LICENSE
-- package.json
-- README.md

It looks like gatsby-node.js is not installed. Re-installing doesn't help.

Could you verify if gatsby-node.js would be installed?

**Comment by kamranayub** [comment]
Ah I may have forgotten to include them in the package, I'll have to issue
a fix. Workaround is to copy the whole folder to the plugins directory at
your root.

**Comment by ronaldborman** [comment]
Thanks! I've copied the folder, and added a copy of gatsby-node..js to it  and it works.

I will leave this issue open for a permanent fix.

**Comment by kamranayub** [comment]
Can you try 1.0.3? I think I fixed it assuming Gatsby finds the code
properly, otherwise I'll need to do another update.

**Comment by ronaldborman** [comment]
I've installed version 1.0.3 and although there now is a src folder with gatsby-node.js in it, there is no message displayed during the PreBootstrap phase saying 'JSON written...' and the example query doesn't work.

However, when I move the file to the root of the directory, everything is ok. So I think gatsby-node.js has to be copied to the root during the plugin installation (and the src folder is then unnecessary).

**Comment by kamranayub** [comment]
Thanks, that's what I wanted to verify. I'll work on doing that!

**Comment by ronaldborman** [comment]
I've just installed version 1.0.4 and can confirm that everything works now ootb.

**Comment by kamranayub** [comment]
Published a new version last night, I think it should work!
