### ISSUE TITLE
Support for latest typedoc version

### ISSUE THREAD

**Issue by saschaklatt** [kamranayub/gatsby-source-typedoc#16]
Hi,

first of all, thank you building this nice plugin :)

However, it seems that the latest version of typedoc `0.20.14` is not yet supported. I used the config from your readme and get errors that the "target" and "mode" options are not supported. Also the GraphQL query of `typedoc.internal.content` just returns a small json string like `"{\"id\":0,\"name\":\"my-docs\",\"kind\":0,\"flags\":{},\"originalName\":\"\"}` instead of the expected typedoc json.

When I use typedoc `0.17.6` though everything works as expected.

It would be great if the latest version would be supported as well.

**Comment by kamranayub** [comment]
Indeed, I ran into this with upgrading Typedoc on our excaliburjs/Excalibur repo too which means this will become a problem with the plugin. I'll try to update soon!

**Comment by kamranayub** [comment]
Looking at this tonight
